# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
use_frameworks!

target 'FireBaseProject' do
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
end

target 'FireBaseProjectTests' do
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
end
